version: "3.9"

networks:
  mlops-network:
    driver: bridge

volumes:
  mlflow-db:
  mlflow-artifacts:

services:

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    container_name: mlflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - mlflow-db:/mlflow/db
      - mlflow-artifacts:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/db/mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
    networks:
      - mlops-network
  api-service:
    build:
      context: .
      dockerfile: Dockerfile     # ← tambah ini
    image: hate-speech-model
    restart: unless-stopped
    ports:
      - "5001-5003:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - REGISTRY_NAME=HateSpeechClassifierV1
    depends_on:
      - mlflow-server
    networks:
      - mlops-network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s